### ISSUE TITLE
Opensource this repo

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/assetbeat#172]
Things to check before we do this:

- [x] There are no internal/private URLs in issues/discussions.
- [x] Correct license is in place
- [x] Documentation is available and updated for all assets inputs
- [x] Naming decisions finalized 
- [x] NOTICE.txt is in place
